# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [40]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-0.0005,  0.0000, -0.0188],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [-0.0394,  0.0000, -0.0390]])


Construct a randomly initialized matrix

In [41]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7076, 0.1886, 0.8855],
        [0.8862, 0.5566, 0.9005],
        [0.2945, 0.3104, 0.9353],
        [0.1345, 0.6558, 0.5934],
        [0.6441, 0.2372, 0.7113]])


Get its size

In [42]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [43]:
x[1:3] = 2
print(x)

tensor([[0.7076, 0.1886, 0.8855],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.1345, 0.6558, 0.5934],
        [0.6441, 0.2372, 0.7113]])


# Assignment

1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [7]:
# 1
x = torch.Tensor(2, 17)
print(x)

tensor([[-0.0005,  0.0000, -0.0005,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000, -0.0005,  0.0000, -0.0194,  0.0000,  0.0000,
          0.0000]])


In [11]:
# 2 
x = torch.FloatTensor(3, 1)
print(x)

tensor([[ 0.0000],
        [ 0.0000],
        [-0.0359]])


In [18]:
# 3 
x = torch.LongTensor(5, 2, 1)
print(x)
x[:] = 7
print(x)

tensor([[[139688341851128],
         [ 94479568642032]],

        [[              0],
         [              0]],

        [[              0],
         [              0]],

        [[              0],
         [              0]],

        [[              0],
         [              0]]])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [36]:
# 4
x = torch.ByteTensor([0,1,1,1,0])
print(x)


tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [44]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.6432, 0.2291, 1.8490],
        [2.6145, 2.5251, 2.8628],
        [2.0480, 2.2726, 2.0917],
        [0.8032, 1.2022, 1.3817],
        [0.7235, 0.6292, 1.1436]])


### 2.2 Addition: syntax 2

In [45]:
print(torch.add(x, y))

tensor([[1.6432, 0.2291, 1.8490],
        [2.6145, 2.5251, 2.8628],
        [2.0480, 2.2726, 2.0917],
        [0.8032, 1.2022, 1.3817],
        [0.7235, 0.6292, 1.1436]])


### 2.3 Addition: giving an output tensor

In [46]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.6432, 0.2291, 1.8490],
        [2.6145, 2.5251, 2.8628],
        [2.0480, 2.2726, 2.0917],
        [0.8032, 1.2022, 1.3817],
        [0.7235, 0.6292, 1.1436]])


### 2.4 Addition: in-place

adds `x`to `y`

In [47]:
y.add_(x)
print(y)

tensor([[1.6432, 0.2291, 1.8490],
        [2.6145, 2.5251, 2.8628],
        [2.0480, 2.2726, 2.0917],
        [0.8032, 1.2022, 1.3817],
        [0.7235, 0.6292, 1.1436]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [48]:
print(x[:, 1])

tensor([0.1886, 2.0000, 2.0000, 0.6558, 0.2372])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiply of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [54]:
# 1
x = torch.rand(3, 1)
y = torch.rand(3, 1)
print(x)
print(y)
print(torch.Tensor.mul(x, y))

tensor([[0.4319],
        [0.4456],
        [0.7966]])
tensor([[0.9643],
        [0.6359],
        [0.2352]])
tensor([[0.4165],
        [0.2834],
        [0.1874]])


0.01201068

In [57]:
# 2
y.add_(x)
print(y)

tensor([[1.3962],
        [1.0815],
        [1.0318]])


In [58]:
# 3
x = torch.rand(3, 1)
y = torch.rand(3, 1)
print(x)
print(y)
print(torch.Tensor.div(x, y))

tensor([[0.8629],
        [0.4980],
        [0.7085]])
tensor([[0.5177],
        [0.7950],
        [0.9595]])
tensor([[1.6669],
        [0.6265],
        [0.7384]])


In [62]:
#
x = torch.rand(2, 4)
y = torch.rand(4, 2)
print(x)
print(y)
print(torch.Tensor.mul(x, y))


AttributeError: 'Tensor' object has no attribute 'T'

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [63]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [64]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [65]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [66]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [71]:
# 1
x_tensor = torch.ones(5, 2)
print(x_tensor)
x_numpy = x.numpy()
print(x_numpy)
x_new = torch.from_numpy(x_numpy)
print(x_new)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [72]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machie.")

CUDA not available on your machie.
